[tool.pyright]
include = ["pim-compiler/src", "pim-compiler/tests", "pim-engine/src", "pim-engine/tests"]
exclude = ["**/node_modules", "**/__pycache__", "build", "dist"]
pythonVersion = "3.10"
pythonPlatform = "Linux"
typeCheckingMode = "basic"
reportMissingImports = true
reportMissingTypeStubs = false
extraPaths = ["pim-compiler/src", "pim-engine/src"]

[tool.pytest.ini_options]
testpaths = ["pim-compiler/tests", "pim-engine/tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-v --tb=short"

[tool.black]
line-length = 100
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/'''

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true