#!/bin/bash

echo "====================================="
echo "PIM Engine v2.0 UI Demo"
echo "====================================="
echo ""
echo "启动主控制器后，可以访问以下界面："
echo ""
echo "1. 控制台（Dashboard）"
echo "   http://localhost:8000/ui/dashboard"
echo "   - 系统概览"
echo "   - 实时统计"
echo "   - 快速操作"
echo ""
echo "2. 模型管理界面"
echo "   http://localhost:8000/ui/models"
echo "   - 加载/卸载模型"
echo "   - 查看模型详情"
echo "   - 快速创建实例"
echo ""
echo "3. 实例管理界面"
echo "   http://localhost:8000/ui/instances"
echo "   - 创建/停止实例"
echo "   - 查看实例状态"
echo "   - 访问实例API"
echo ""
echo "4. API 文档"
echo "   http://localhost:8000/docs"
echo "   - REST API 文档"
echo "   - 在线测试"
echo ""
echo "====================================="
echo "启动命令："
echo "cd pim-engine/src && python main.py"
echo "====================================="