#!/usr/bin/env python3
"""PIM Compiler executable"""

import sys
import os

# 添加src目录到Python路径
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

from cli.main import main

if __name__ == '__main__':
    sys.exit(main())